const dataForPaginator = [
  {
    id: 1,
    title: "accusamus beatae ad facilis cum similique qui sunt",
    url: "https://via.placeholder.com/600/92c952",
    userImage: "https://via.placeholder.com/150/92c952",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 2,
    title: "reprehenderit est deserunt velit ipsam",
    url: "https://via.placeholder.com/600/771796",
    userImage: "https://via.placeholder.com/150/771796",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 3,
    title: "officia porro iure quia iusto qui ipsa ut modi",
    url: "https://via.placeholder.com/600/24f355",
    userImage: "https://via.placeholder.com/150/24f355",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 4,
    title: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
    url: "https://via.placeholder.com/600/d32776",
    userImage: "https://via.placeholder.com/150/d32776",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    url: "https://via.placeholder.com/600/f66b97",
    userImage: "https://via.placeholder.com/150/f66b97",
    redirectLink: "https://jsonplaceholder.typicode.com",
    category: "Design",
  },
];
const dataForCoursesSlider = [
  {
    id: 1,
    personImg: "img/course/persone/first.jpg",
    backUrl: "img/course/itemBack/first.jpg",
    category: "Design",
    title: "Learn Photoshop title",
    price: "260",
    oldPrice: "360",
    countOfStars: 4.2,
  },
  {
    id: 2,
    personImg: "img/course/persone/third.jpg",
    backUrl: "img/course/itemBack/second.jpg",
    category: "Marketing",
    title: " Learn Photoshop title trun",
    price: "260",
    oldPrice: "360",
    countOfStars: 4,
  },
  {
    id: 3,
    personImg: "img/course/persone/second.jpg",
    backUrl: "img/course/itemBack/third.jpg",
    category: "Web design",
    title: "Learn Photoshop",
    price: "260",
    oldPrice: "360",
    countOfStars: 5,
  },
  {
    id: 4,
    personImg: "img/course/persone/third.jpg",
    backUrl: "img/course/itemBack/second.jpg",
    category: "Test Slide",
    title: "Learn Photoshop test",
    price: "260",
    oldPrice: "360",
    countOfStars: 2.5,
  },
];
const dataForCustomersSlider = [
  {
    imgUrl:
      "https://img.freepik.com/fotos-kostenlos/schliessen-sie-herauf-mann-der-code-auf-dem-laptop-schreibt_158595-5169.jpg?w=900&t=st=1667926250~exp=1667926850~hmac=9b14d736ec96f8b12087148cd023bd39ebfc67172d5f5762ea33d616a0506f30",
    color: "red",
    text: "An investment in knowledge always pays the best interest. <br> <br> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos accusantium, illo eveniet, in pariatur eum dolore dolorum quis ad quasi, laboriosam ex? Doloremque explicabo, perspiciatis fugit suscipit quod ipsa quae.",
    author: "Benjamin Franklin",
  },
  {
    imgUrl:
      "https://img.freepik.com/fotos-kostenlos/mitarbeiter-eines-it-unternehmens-die-an-einem-computer-arbeiten_1303-19428.jpg?w=900&t=st=1667926529~exp=1667927129~hmac=07404a17c3337a4f2415822687cec6446ffad9c066831fd54df34af87e76159b",
    color: "blue",
    text: "Wisdom is knowing how little we know <br> <br> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos accusantium, illo eveniet, in pariatur eum dolore dolorum quis ad quasi, laboriosam ex? Doloremque explicabo, perspiciatis fugit suscipit quod ipsa quae.",
    author: "Oscar Wilde",
  },
];
export { dataForPaginator, dataForCoursesSlider, dataForCustomersSlider };
